### ISSUE TITLE
Consider adding some way to retrieve secondary keys when using IDBIndex.getAllKeys

### ISSUE THREAD

**Issue by malibuzios** [w3c/IndexedDB#71] opened 2016-03-19 13:17 UTC
When using `IDBIndex.openKeyCursor` to retrieve all (index) keys satisfying some range, I can easily get the secondary key (the value of the property indexed for that particular record) in addition to the primary one, for example:

``` js
...
let results = [];

let cursorRequest = objectStore.index("myIndex").openKeyCursor(range);

cursorRequest.onsuccess = (event) => {
    let cursor = event.target.result;

    if (cursor) {
        results.push({ primaryKey: cursor.primaryKey, key: cursor.key });
        cursor.continue();
    }
    else {
        resolve(results);
    }
}
...
```

It seems that `IDBIndex.getAllKeys` currently only returns the primary keys (tested on latest stable Firefox/Chrome versions). Is/will there be any way to retrieve the secondary keys as well? or falling back to using cursors is planned to remain the most efficient solution?

**Comment by tophf** [comment] 2019-04-20 20:37
In my tests IDBIndex.openKeyCursor on 4000 of relatively simple records seems to be practically unusable in Chrome - 150ms compared to 15ms of IDBIndex.getAllKeys.

**Comment by inexorabletash** [comment] 2019-09-20 00:53
https://github.com/w3c/IndexedDB/issues/206 is a dupe of this, but has more context.

**Closed by inexorabletash** 2019-09-20 00:53 UTC
Labels: duplicate, feature request, indexes, queries
