### ISSUE TITLE
Remove DOMStringList

### ISSUE THREAD

**Issue by Ms2ger** [w3c/IndexedDB#128] opened 2016-12-13 13:05 UTC
Adding this here when we're trying to remove it from the platform seems pretty backwards.

**Comment by beidson** [comment] 2016-12-13 14:55
Was there a new usage of DOMStringList added to IDB 2.0?

If so I agree it should be removed.

But Afaik the DOMStringList usage is preexisting from IDB 1.0

**Comment by Ms2ger** [comment] 2016-12-13 17:04
I don't understand what, if any, conclusion you expect people to infer from your comment.

**Comment by inexorabletash** [comment] 2016-12-13 17:07
Duplicate of https://github.com/w3c/IndexedDB/issues/28

**Closed by inexorabletash** 2016-12-13 17:07 UTC
