### ISSUE TITLE
"If an exception was propagated out from any event handler" is not a thing

### ISSUE THREAD

**Issue by annevk** [w3c/IndexedDB#140] opened 2017-01-21 10:27 UTC
While reading through #87 I found Indexed DB has been monkey patching DOM as well with something that is not supported by the event dispatch algorithm. The event dispatch algorithm handles its own exceptions and reports them to window.onerror. It seems you're trying to hook into that somehow.

**Comment by annevk** [comment] 2017-01-21 10:27
In particular in 7.5 of https://w3c.github.io/IndexedDB/#upgrade-transaction-steps.

**Comment by inexorabletash** [comment] 2017-01-22 01:46
Nicely spotted.  This has been in the spec since forever (early iterations of v1) and behavior is consistent across browsers, so we may need another hook unless someone can come up with a clever way of describing this.

(Hopefully there aren't too many more monkey patches lurking?).

**Comment by annevk** [comment] 2017-01-22 08:59
Does the error still go to `window.onerror`? We don't really have a concept of UA-event-listeners, so I suspect we need some kind of hook.

**Comment by inexorabletash** [comment] 2017-01-23 04:49
I haven't spec'd window.onerror integration yet (see https://github.com/w3c/IndexedDB/issues/49) -  it's implemented in Firefox but not Chrome. (I hit a performance regression whenever I try, and then get distracted by other shiny things.) Since IDB is exposed in workers there was apparently some trickiness on the spec side too, but that may have been sorted out.

But in Firefox, yes - an error from a request that does not have `preventDefault()` called on the event causes the transaction to abort and propagates to window.onerror, but by the time it hits the global error handler it's too late to "preventDefault()" and stop the transaction from aborting.

**Comment by annevk** [comment] 2017-01-23 09:15
If you call preventDefault() and then throw, it would not abort? That doesn't seem to be specified. But I guess the cleanest integration would be to change how dispatch works. Either we need to return more information than just a boolean, or you need to pass something in that gets modified (which is somewhat ugly I think, but okay).

**Comment by inexorabletash** [comment] 2017-01-23 17:50
Sorry, was mostly asleep - I was thinking about the error event case, not the exception case. I'll do some testing about preventDefault() vs. throwing and report back.

And either approach (additional return value or an "out" parameter or callback) is fine with me.

**Comment by inexorabletash** [comment] 2017-02-13 23:02
Oh yes, needed to follow up here.

PR for tests added.  As expected, preventDefault() doesn't change behavior.  And behavior is the same across event handlers/listeners, and (in the case of error) how far the event has bubbled.

**Comment by annevk** [comment] 2017-02-14 10:09
I created a hook for the "dispatch" algorithm that you can use.

**Comment by inexorabletash** [comment] 2017-03-07 17:14
Resolved in https://github.com/w3c/IndexedDB/commit/214a1357f690640615ad5b395cf96ffc2de61da3

Thanks all!

**Closed by inexorabletash** 2017-03-07 17:14 UTC
Labels: PR posted, spec issue
