### ISSUE TITLE
index sorting

### ISSUE THREAD

**Issue by aphillips** [w3c/IndexedDB#173] opened 2017-03-23 22:47 UTC
https://www.w3.org/TR/IndexedDB-2/#index-construct

>    The records in an index are always sorted according to the record's key.

This allows for an index sorted by code unit, but this is often not the most useful sort order. Being able to define a natural language sort, such as one based on UCA, would be extremely useful. Otherwise implementations have to obtain the complete list of records and sort them in memory--which is kind of beside the point. Features such as key ranges and cursors are much less valuable if the database cannot be sorted in this way.

**Comment by aphillips** [comment] 2017-03-23 22:47
This is https://github.com/w3c/i18n-activity/issues/368 (please add i18n-comment label)

**Comment by inexorabletash** [comment] 2017-03-23 23:11
This is a duplicate of https://github.com/w3c/IndexedDB/issues/38

**Comment by inexorabletash** [comment] 2019-09-20 05:06
**TPAC 2019 Web Apps Indexed DB triage notes:**

The title is more generic than #38, but the description is the same issue. Closing as duplicate.

**Closed by inexorabletash** 2019-09-20 05:06 UTC
Labels: duplicate, feature request, i18n-comment
