### ISSUE TITLE
Durable database writes

### ISSUE THREAD

**Issue by wcalderw** [w3c/IndexedDB#99] opened 2016-10-20 13:39 UTC
We need a way to force data writes to disk to prevent loss of data in the event the app/database is "stopped". Firefox has implemented an experimental mode "readwriteflush" that can be used on a transaction such that when oncomplete event happens with success you can be sure that the data made it to the disk. This circumvents the "write cache" that has been implemented in Indexeddb and impacts performance, but for those of use that must ensure data is permanently stored this is a trade off we are willing to have.

As it stands. We have observed Edge Windows 10 1607 (OS level write caching turned off) IndexedDB can take 1 to 15+ minutes before committing a write to disk. We are testing with other systems (Android, IOS, etc) as well, but suspect the same behavior.

**Comment by beidson** [comment] 2016-10-20 15:55
WebKit is certainly not interested in adding any new web APIs that involve synchronous i/o, which is basically what is being asked for here.

Are you actually finding in other implementations that *after* a transaction commits, there's a *15 minute* window where the bits are not written to disk?

That sounds like an issue to raise with those implementations specifically.

**Comment by inexorabletash** [comment] 2016-10-20 16:23
For reference, Chrome does not fire `complete` until the transaction has flushed to disk. This happens in a different process from the page so does not block any event loops.

**Comment by wcalderw** [comment] 2016-10-20 17:16
We are still investigating other platforms (Android Chromium and IOS WebKit). If chrome is actually generating the complete as suggested then at least that may solve one of the 3 platforms for us. Windows has been a real pain as far as app limitations and short commings... I'll follow up here after we've looked at android.

**Comment by inexorabletash** [comment] 2017-01-14 00:30
@wcalderw - any feedback?

**Comment by wcalderw** [comment] 2017-01-14 02:31
We moved to a cordova provided no sql solution on windows 10 to avoid the
problem. Was really frustrating to have a success on a data submission only
to find it's not really saved though... Seems like a non starter for a
database solution.

**Comment by wcalderw** [comment] 2017-01-14 02:34
Oh and we still haven't received any response from Microsoft on this.
Despite them making our submitted issue critical.

**Comment by inexorabletash** [comment] 2019-06-14 22:31
For performance reasons, we (Chrome) are considering making the flush optional. Example:

```js
db.transaction(scope, "readwrite", {flush: false});
```

(Having the default be truthy is annoying, but there's no good antonym. Suggestions?)

Thoughts?

**Comment by domenic** [comment] 2019-06-14 22:33
preventFlush: true?

**Comment by inexorabletash** [comment] 2019-06-14 22:38
Maybe. Feels like a double-negative. [ref](https://w3ctag.github.io/design-principles/#prefer-dict-to-bool)

**Comment by domenic** [comment] 2019-06-14 22:39
We've done it a few times, e.g. `.focus({ preventScroll: true })`.

**Comment by inexorabletash** [comment] 2019-06-14 23:05
I guess this is a dupe of https://github.com/w3c/IndexedDB/issues/50 ... let me close it out and move the comments there.

**Closed by inexorabletash** 2019-06-14 23:05 UTC
Labels: TPAC 2019
